fix: invalid json checking
sasjs/adapter pull request #462
Opened 2021-07-09 11:53 UTC by medjedovicm

## Issue

#431 

## Intent

Fixing the initial mechanism

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all four of the items below are confirmed!  If an urgent fix is needed - use a tar file.

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] All unit tests are passing (`npm test`).
![image](https://user-images.githubusercontent.com/18329105/125073963-f98a5c80-e0bc-11eb-94fc-408ca001726d.png)
- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
![sasjs-tests](https://user-images.githubusercontent.com/18329105/125073822-d2338f80-e0bc-11eb-993f-a1ae380531b8.png)

2021-07-10 09:36 UTC, sabhas submitted a review, later dismissed

2021-07-10 10:45 UTC, allanbowe commented on src/utils/isValidJson.ts
> +    str = typeof str !== 'string' ? JSON.stringify(str) : str
If it is an object, why would we need to check if it is valid json?

2021-07-10 10:48 UTC, allanbowe requested changes

2021-07-10 10:48 UTC, allanbowe commented on src/utils/isValidJson.ts
> +export const isValidJson = (str: string | object) => {
If it is an object, why would we need to JSON parse it?

2021-07-12 11:35 UTC, krishna-acondy submitted a review, later dismissed

2021-07-12 11:35 UTC, krishna-acondy commented on src/test/utils/isValidJson.spec.ts
> +describe.only('jsonValidator', () => {
Only should be removed.

2021-07-12 13:44 UTC, sabhas approved these changes

2021-07-14 17:23 UTC, VladislavParhomchik approved these changes

2021-07-14 17:45 UTC, allanbowe approved these changes

2021-07-14 17:46 UTC, merged