feat(auth): added multi-language support to logIn method
sasjs/adapter pull request #836
Opened 2024-06-20 14:18 UTC by YuryShkoda

## Issue

Closes #835 

## Intent

- Add multi-language support to `logIn` method of the `AuthManager`.

## Implementation

- Added `successHeaders` property to the `AuthManager`.
- Added `isLogInSuccessHeaderPresent` method to the `AuthManager`.
- Added `getUserLanguage` utility.

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [ ] Unit tests coverage has been increased and a new threshold is set.
- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- (CI Runs this) All `sasjs-tests` are passing. If you want to run it manually (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
- [ ] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya

2024-06-20 14:50 UTC, medjedovicm requested changes

2024-06-20 14:50 UTC, medjedovicm commented on src/auth/AuthManager.ts
> +    en: enLoginSuccessHeader,
I see that `enLoginSuccessHeader` is used in multiple files (check references). I suppose this list should be used in those places as well. Also would be nice to have a single reusable source of this list, in the project.

Example:
![image](https://github.com/sasjs/adapter/assets/18329105/80d93056-82c9-4109-8179-35b85084227a)

2024-06-20 14:50 UTC, medjedovicm commented on src/auth/verifySas9Login.ts
> +      loginPopup.window.document.body.innerText.includes(enLoginSuccessHeader)
Why did we hardcoded `EN`glish?

2024-06-20 14:50 UTC, medjedovicm commented on src/auth/verifySasViyaLogin.ts
> +      loginPopup.window.document.body?.innerText?.includes(enLoginSuccessHeader)
Why did we hardcoded `EN`glish?

2024-06-21 12:39 UTC, allanbowe approved these changes

2024-06-21 12:40 UTC, merged

2024-06-21 13:57 UTC, gh4nh commented
@allanbowe I've downloaded and implemented the index.min.js and successfully tested with a German and English browser. Thank you for your speedy fix.