Issue90
sasjs/adapter pull request #91
Opened 2020-09-15 11:18 UTC by medjedovicm

Closes #90

2020-09-15 11:22 UTC, YuryShkoda approved these changes

2020-09-15 11:22 UTC, krishna-acondy commented
@medjedovicm Looks like the build failed. Could you take a look please?

2020-09-15 11:25 UTC, allanbowe approved these changes

2020-09-15 11:28 UTC, krishna-acondy requested changes
One other thing - please regenerate the TypeDoc docs so the new type is included.

2020-09-17 07:26 UTC, allanbowe submitted a review, later dismissed

2020-09-18 15:42 UTC, krishna-acondy approved these changes

2020-09-18 15:44 UTC, merged