Issue87
sasjs/adapter pull request #92
Opened 2020-09-15 11:35 UTC by medjedovicm

Closes #87

2020-09-15 11:37 UTC, krishna-acondy submitted a review, later dismissed

2020-09-16 05:44 UTC, YuryShkoda requested changes

2020-09-16 05:44 UTC, YuryShkoda commented on src/SASViyaApiClient.ts
> +        console.error('Job was not found.')
delete extra console.error()

2020-09-16 05:44 UTC, YuryShkoda commented on src/SASViyaApiClient.ts
> +        console.error('Job definition URI was not found.')
delete extra console.error()

2020-09-18 05:41 UTC, YuryShkoda approved these changes

2020-09-18 05:42 UTC, merged